name: ${project.name}
main: ${project.plugin.main}
version: ${project.plugin.version}
author: ${project.plugin.author}

commands:
  spamunban:
    description: Unbans a player banned by SpamHammer.
    usage: /<command> PLAYER_NAME - unbans the specified player if they were banned by SpamHammer.
  spamunmute:
    description: Unmutes a player banned by SpamHammer.
    usage: /<command> PLAYER_NAME - unmutes the specified player if they were muted by SpamHammer.
  spamreset:
    description: Resets a player's SpamHammer punishment level.
    usage: /<command> PLAYER_NAME - resets the punishment process for the specified player.
    
permissions:
  spamhammer.*:
    description: Give access to all spamhammer commands.
    children:
      spamhammer.unban: true
      spamhammer.unmute: true
      spamhammer.reset: true
      spamhammer.ignore: true
  spamhammer.unban:
    description: Allows use of /spamunban.
    default: op
  spamhammer.unmute:
    description: Allows use of /spamunmute.
    default: op
  spamhammer.reset:
    description: Allows use of /spamreset.
    default: op
  spamhammer.ignore:
    description: Exempts players from spamhammer.
    default: op
